[package]
name = "gameoflife"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beryllium = "0.13.3"
fermium = "22605.0.0"
rand = "0.8.5"

